#!/usr/bin/env python

import os, glob
import subprocess
import shutil
import re
import zipfile
from pathlib import Path

max_chunk_sum = 1024 * 1024 * 1024

def compress_file(c, path, opth):
    root_directory = Path(c)
    lst = [(f.stat().st_size, str(f.resolve())) for f in root_directory.glob('**/*') if f.is_file()]
    print(lst)
    result = [[]]
    cur = 0
    for item in lst:
        d = os.path.relpath(item[1], path)
        if cur + item[0] > max_chunk_sum:
            result.append([d])
            cur = 0
        else:
            result[-1].append(d)
            cur = cur + item[0]
    for i,e in enumerate(result):
        archn = os.path.join(opth, os.path.basename(os.path.normpath(c)) + ".part" +str(i)+ ".zip")
        print(archn)
        with zipfile.ZipFile(archn, 'w', zipfile.ZIP_STORED) as zipf:
            for file in e:
                zipf.write(file)
                os.remove(file)
    shutil.rmtree(c, ignore_errors=True)

def compress():
    path = os.getcwd()
    ipth = os.path.join(path, 'input')
    opth = os.path.join(path, 'output')
    files = glob.glob(ipth + "/*/")
    for c in files:
        compress_file(c, path, opth)

compress()