#!/usr/bin/env python

import os, glob

def rename_files(ext):
    path = os.getcwd()
    files = glob.glob(path + '/*.' + ext)
    print(files)
    for f in files:
        arr = f.split(".")
        modified = arr[-2]
        if (modified.find("part") >= 0 and modified.find("-") >= 0):
            newmod = modified.split("-")[0]
            arr[-2] = newmod
            finalname = ".".join(arr)
            os.rename(f, finalname)

rename_files("rar")